import './globals.css';
import { Arimo } from 'next/font/google';
import { Providers } from './providers';
import Header from '@/components/layout/header';

const arimo = Arimo({
  subsets: ['latin', 'hebrew'],
  weight: ['400', '700'],
  style: ['italic'],
  display: 'swap',
});

export const metadata = {
  title: 'OhGus Blog',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="ko">
      <body
        className={`antialiased min-h-screen bg-[#F3F1F5] dark:bg-[#161716] text-[#252B52] dark:text-[#F3F1F5] ${arimo.className}`}
      >
        <Providers>
          <Header />
          <main className="mt-5 mx-auto max-w-3xl px-2">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
