import "./globals.css"
import { Inter } from "next/font/google"
import { Providers } from "./providers";
import Header from "@/components/layout/header";

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "OhGus Blog",
  description: "Generated by create next app",
}

interface RootLayoutProps {
  children: React.ReactNode
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="ko">
      <body className={`mt-5 mx-auto max-w-3xl antialiased min-h-screen bg-orange-50 dark:bg-stone-800 text-slate-900 dark:text-slate-50 ${inter.className}`}>
        <Providers>
          <Header />
          <main>{children}</main>
        </Providers>
      </body>
    </html>
  )
}
